bash build.sh x64 client
bash build.sh x64 router
bash build.sh x86 client
bash build.sh x86 router
bash build.sh arm client
bash build.sh arm router
bash build.sh arm64 client
bash build.sh arm64 router
bash build.sh mips client
bash build.sh mips router
bash build.sh freebsd client
bash build.sh freebsd router
